# Basic smoke-test for Grapnel
# Exercises basic install facilities and specifcation parsing

[timber]
import = "github.com/ngmoco/timber"

[memcache]
import = "github.com/bradfitz/gomemcache"
tag = "release.r60"

[mux]
import = "github.com/gorilla/mux"

[toml]
import = "github.com/pelletier/go-toml"
tag = "23d36c08ab90f4957ae8e7d781907c368f5454dd"
