[[rewrite]]
[rewrite.match]
  import = ".+"
  url = "^$"
[rewrite.replace]
  url = "http://{{.import}}"

[[rewrite]]
[rewrite.match]
  import = "^$"
  url = ".+"
[rewrite.replace]
  import = "{{.host}}/{{.path}}"

[[rewrite]]
[rewrite.match]
  type = "^$"
  scheme = "git"
[rewrite.replace]
  type = "git"

[[rewrite]]
[rewrite.match]
  type = "^$"
  path = '.*\.git'
[rewrite.replace]
  type = "git"

[[rewrite]]
[rewrite.match]
  type = "^$"
  import = 'github.com/.*'
[rewrite.replace]
  type = "git"

[[rewrite]]
[rewrite.match]
  type = "^$"
  host = "github.com"
[rewrite.replace]
  type = "git"

[[rewrite]]
[rewrite.match]
  host = 'gopkg\.in'
[rewrite.replace]
  branch = '{{replace .path "^.*\\.(.*)$" "$1"}}'
  path = '{{replace .path "^(.*)\\..*$" "$1"}}'
  host = 'github.com'
  type = 'git'
